name: Resume CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Install typst
        uses: typst-community/setup-typst@v3
        with:
          typst-version: 0.12.0

      - name: Build resumes
        run: ./scripts/compile.sh

      - name: Get current date
        if: ${{ github.repository == 'Its-Alex/resume' && contains(github.ref, 'refs/heads/master') }}
        id: date
        run: echo "DATE=$(date +%Y-%m-%d-%H:%M)" >> $GITHUB_ENV

      - name: Release
        if: ${{ github.repository == 'Its-Alex/resume' && contains(github.ref, 'refs/heads/master') }}
        uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Development Build"
          files: |
            *.pdf
